packages:
    - "packages/*"
    - "examples/*"

catalog:
    typescript: ^5.8.2
    vitest: ^3.0.9
    tsdown: ^0.14.1
    "@biomejs/biome": ^2.0.0-beta.1
    "vite": ^6.3.6
    "@types/node": ^20.19.0
